# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from ai.get_photo import get_photo
from ai.register_face import check_registration
import sqlite3
import sys

surname_user = ""

class StartApp(object):
    def add_user(self):
        self.name_user = self.name_input.text()
        self.surname_user = self.surname_input.text()
        self.numberCard_user = self.numberCard_input.text()
        self.date_user = self.lineEdit_5.text()
        self.cvv_user = self.lineEdit_6.text()
        connection = sqlite3.connect(r'C:\Users\Airat\PycharmProjects\BayMax_Bank\users.db')
        cursor = connection.cursor()
        cursor.execute('INSERT INTO Users (name, surname, card, cvv, date) VALUES (?, ?, ?, ?, ?)', (self.name_user, self.surname_user, self.numberCard_user, self.cvv_user, self.date_user))
        connection.commit()
        connection.close()
        try:
            get_photo(name=f'{self.surname_user} {self.name_user}')
            self.registartion_info.setText('Регистрация прошла успешно')
        except:
            self.registartion_info.setText('Попробуйте заново, возникла ошибка...')

    def check_user(self):
        self.fio = self.input_sign_in.text()
        self.fio = self.fio.split()
        self.name = self.fio[0]
        self.surname = self.fio[1]
        connection = sqlite3.connect(r'C:\Users\Airat\PycharmProjects\BayMax_Bank\users.db')
        cursor = connection.cursor()
        self.result = cursor.execute("SELECT * FROM Users WHERE surname=?", (self.surname,)).fetchall()
        if len(self.result) == 0:
            self.sign_in_info.setText('Данного пользователя не существует')
        else:
            print('OK')
            if check_registration(check_name=f'{self.surname} {self.name}'):
                global surname_user
                surname_user = self.surname
                self.sign_in_info.setText('Вход в аккаунт произошел успешно. Закройте приложение')


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 871, 631))
        self.tabs.setObjectName("tabs")
        self.StartPage = QtWidgets.QWidget()
        self.StartPage.setObjectName("StartPage")
        self.label = QtWidgets.QLabel(self.StartPage)
        self.label.setGeometry(QtCore.QRect(340, 60, 101, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.png"))
        self.label.setObjectName("label")
        self.version = QtWidgets.QLabel(self.StartPage)
        self.version.setGeometry(QtCore.QRect(580, 500, 231, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.version.setFont(font)
        self.version.setObjectName("version")
        self.title1 = QtWidgets.QLabel(self.StartPage)
        self.title1.setGeometry(QtCore.QRect(180, 160, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title1.setFont(font)
        self.title1.setObjectName("title1")
        self.title2 = QtWidgets.QLabel(self.StartPage)
        self.title2.setGeometry(QtCore.QRect(100, 200, 621, 31))
        self.title2.setObjectName("title2")
        self.buttonRegistration = QtWidgets.QPushButton(self.StartPage)
        self.buttonRegistration.setGeometry(QtCore.QRect(80, 260, 281, 231))
        self.buttonRegistration.setObjectName("buttonRegistration")
        self.buttonRegistration.clicked.connect(lambda: self.tabs.setCurrentIndex(2))
        self.buttonSignIn = QtWidgets.QPushButton(self.StartPage)
        self.buttonSignIn.setGeometry(QtCore.QRect(450, 260, 281, 231))
        self.buttonSignIn.setObjectName("buttonSignIn")
        self.buttonSignIn.clicked.connect(lambda: self.tabs.setCurrentIndex(1))
        self.tabs.addTab(self.StartPage, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.input_sign_in = QtWidgets.QLineEdit(self.tab)
        self.input_sign_in.setGeometry(QtCore.QRect(20, 180, 741, 71))
        self.input_sign_in.setObjectName("input_sign_in")
        self.title3 = QtWidgets.QLabel(self.tab)
        self.title3.setGeometry(QtCore.QRect(180, 110, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title3.setFont(font)
        self.title3.setObjectName("title3")
        self.logo2 = QtWidgets.QLabel(self.tab)
        self.logo2.setGeometry(QtCore.QRect(340, 10, 101, 101))
        self.logo2.setText("")
        self.logo2.setPixmap(QtGui.QPixmap("logo.png"))
        self.logo2.setObjectName("logo2")
        self.sign_in_text = QtWidgets.QLabel(self.tab)
        self.sign_in_text.setGeometry(QtCore.QRect(230, 260, 321, 21))
        self.sign_in_text.setObjectName("sign_in_text")
        self.sign_in_info = QtWidgets.QLabel(self.tab)
        self.sign_in_info.setGeometry(QtCore.QRect(270, 450, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sign_in_info.setFont(font)
        self.sign_in_info.setObjectName("sign_in_info")
        self.sign_in_button = QtWidgets.QPushButton(self.tab)
        self.sign_in_button.setGeometry(QtCore.QRect(200, 320, 411, 81))
        self.sign_in_button.setObjectName("sign_in_button")
        self.sign_in_button.clicked.connect(self.check_user)
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.title4 = QtWidgets.QLabel(self.tab_2)
        self.title4.setGeometry(QtCore.QRect(170, 130, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title4.setFont(font)
        self.title4.setObjectName("title4")
        self.logo3 = QtWidgets.QLabel(self.tab_2)
        self.logo3.setGeometry(QtCore.QRect(330, 30, 101, 101))
        self.logo3.setText("")
        self.logo3.setPixmap(QtGui.QPixmap("logo.png"))
        self.logo3.setObjectName("logo3")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(20, 180, 191, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(20, 210, 141, 21))
        self.label_12.setObjectName("label_12")
        self.date_input = QtWidgets.QLabel(self.tab_2)
        self.date_input.setGeometry(QtCore.QRect(20, 260, 211, 31))
        self.date_input.setObjectName("date_input")
        self.cvv_input = QtWidgets.QLabel(self.tab_2)
        self.cvv_input.setGeometry(QtCore.QRect(20, 290, 231, 31))
        self.cvv_input.setObjectName("cvv_input")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(20, 230, 121, 31))
        self.label_16.setObjectName("label_16")
        self.name_input = QtWidgets.QLineEdit(self.tab_2)
        self.name_input.setGeometry(QtCore.QRect(190, 180, 411, 20))
        self.name_input.setObjectName("name_input")
        self.surname_input = QtWidgets.QLineEdit(self.tab_2)
        self.surname_input.setGeometry(QtCore.QRect(130, 210, 411, 20))
        self.surname_input.setObjectName("surname_input")
        self.numberCard_input = QtWidgets.QLineEdit(self.tab_2)
        self.numberCard_input.setGeometry(QtCore.QRect(150, 240, 411, 20))
        self.numberCard_input.setObjectName("numberCard_input")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 270, 411, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 300, 411, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.registration_button = QtWidgets.QPushButton(self.tab_2)
        self.registration_button.setGeometry(QtCore.QRect(210, 330, 361, 61))
        self.registration_button.setObjectName("registration_button")
        self.registration_button.clicked.connect(self.add_user)
        self.registartion_info = QtWidgets.QLabel(self.tab_2)
        self.registartion_info.setGeometry(QtCore.QRect(230, 400, 331, 81))
        self.registartion_info.setObjectName("registartion_info")
        self.tabs.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.version.setText(_translate("MainWindow", "BAYMAX Safety System. 2024-2025"))
        self.title1.setText(_translate("MainWindow", "BAYMAX - Система безопасности для банкоматов"))
        self.title2.setText(_translate("MainWindow", "Если Вы не зарегистрированны в системе, Вам следует пройти регистрацию. Если у Вас есть аккаунт, войдите в него"))
        self.buttonRegistration.setText(_translate("MainWindow", "Регистрация"))
        self.buttonSignIn.setText(_translate("MainWindow", "Вход в аккаунт"))
        self.tabs.setTabText(self.tabs.indexOf(self.StartPage), _translate("MainWindow", "Start Page"))
        self.title3.setText(_translate("MainWindow", "BAYMAX - Система безопасности для банкоматов"))
        self.sign_in_text.setText(_translate("MainWindow", "Введите имя и фамилию с обратной стороны вашей карточки"))
        self.sign_in_info.setText(_translate("MainWindow", "ВВЕДИТЕ ВСЕ НЕОБХОДИМЫЕ ДАННЫЕ!"))
        self.sign_in_button.setText(_translate("MainWindow", "Войти в аккаунт..."))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("MainWindow", "Sign In"))
        self.title4.setText(_translate("MainWindow", "BAYMAX - Система безопасности для банкоматов"))
        self.label_11.setText(_translate("MainWindow", "Введите имя(как на карточке): "))
        self.label_12.setText(_translate("MainWindow", "Введите фамилию: "))
        self.date_input.setText(_translate("MainWindow", "Введите дату окончания работы карты: "))
        self.cvv_input.setText(_translate("MainWindow", "Введите CVV код: "))
        self.label_16.setText(_translate("MainWindow", "Введите номер карты:"))
        self.registration_button.setText(_translate("MainWindow", "Пройти регистрацию..."))
        self.registartion_info.setText(_translate("MainWindow", "Введите все необходимые данные!"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("MainWindow", "Registration"))


def run_startApp() -> str:
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = StartApp()
    ui.setupUi(MainWindow)
    MainWindow.show()
    app.exec_()
    return surname_user


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = StartApp()
    ui.setupUi(MainWindow)
    MainWindow.show()
    app.exec_()
    print('Вход в аккаунт выполнен успешно✅✅✅')
